# Generated by Django 4.1.7 on 2023-05-25 17:38

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(default='', max_length=30)),
                ('last_name', models.CharField(default='', max_length=30)),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('nickname', models.CharField(max_length=100, unique=True, verbose_name='nickname')),
                ('password', models.CharField(max_length=200, validators=[django.core.validators.MinLengthValidator(8)])),
            ],
        ),
    ]
